---
title: "smoking"
author: "John Dou"
date: "August 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install relevant packages

```{r, eval=FALSE}
devtools::install_github('BioinformaticsFMRP/TCGAbiolinks')

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("sva")
BiocManager::install("minfi")
BiocManager::install("limma")
BiocManager::install("IlluminaHumanMethylation450kmanifest")
BiocManager::install("IlluminaHumanMethylation450kanno.ilmn12.hg19")
BiocManager::install("sva")
BiocManager::install("bacon")
BiocManager::install("BiocParallel")
BiocManager::install("FGNet")

install.packages("matrixStats")
install.packages("MASS")
install.packages("abind")
install.packages("Hmisc")
install.packages('VennDiagram')
install.packages("qqman")

```

## Download TCGA data

```{r, eval=FALSE}
library(TCGAbiolinks)

#where you want to save downloaded data from TCGA
SAVE_HERE <- '/nfs/turbo/bakulski1/People/johndou/Smoking/tcga_data/'

#where you want files for preprocessing steps
PREPROCESS_HERE <- '/nfs/turbo/bakulski1/People/johndou/Smoking/preprocess/'

setwd(SAVE_HERE)

query <- GDCquery(project = "TCGA-LUAD",
                  data.category = "Raw microarray data",
                  data.type = "Raw intensities", 
                  experimental.strategy = "Methylation array", 
                  legacy = TRUE,
                  file.type = ".idat",
                  platform = "Illumina Human Methylation 450")

#make file to map cases to idats
match.file.cases <- getResults(query,cols=c("cases","file_name"))
match.file.cases$Basename <- substr(match.file.cases$file_name,1,17)
match.file.cases$bcr_patient_barcode <- substr(match.file.cases$cases,1,12)
save(match.file.cases,file='match.file.cases.rda')

#download idats, don't do this at home
tryCatch(GDCdownload(query, method = "api",chunks.per.download = 20),
         error = function(e) GDCdownload(query, method = "client"))

for(file in dir(".",pattern = ".idat", recursive = T)){
  TCGAbiolinks::move(file,basename(file))
}


### download clinical data 
query <- GDCquery(project = "TCGA-LUAD", 
                  data.category = "Clinical", 
                  data.type = "Clinical data",
                  legacy = TRUE,
                  file.type='txt')
clinical.biotab <- GDCprepare(query)
cl.luad <- clinical.biotab$clinical_patient_luad
cl.luad <- data.frame(cl.luad)
cl.luad <- cl.luad[-c(1,2),]
save(cl.luad,file='cl.luad.rda')


### merge file names (basenames) and clinical data
base <- match.file.cases[,c('cases','Basename','bcr_patient_barcode')]
dim(base)
#rows should be cut in half because no longer two entries sample for red/green
base <- unique(base)
dim(base)

pd <- merge(base,cl.luad,by='bcr_patient_barcode',all.x=T,all.y=F)
rownames(pd) <- pd$Basename
dim(pd)
saveRDS(pd,file=paste0(PREPROCESS_HERE,'pd.rds'))

```

## Loading in idats and preprocessing

```{r, eval=FALSE}
library(matrixStats)
library(minfi)

#base folder of where the idats are located
IDAT_FOLDER_PATH <- "/nfs/turbo/bakulski1/People/johndou/Smoking/tcga_data/TCGA-LUAD"

#where you want files involved in preprocessing steps saved
PREPROCESS_HERE <- '/nfs/turbo/bakulski1/People/johndou/Smoking/preprocess/'

#where cross reactive probe list from (Chen et al. 2013) is located
CROSS_PATH <- "/nfs/turbo/bakulski1/People/johndou/Smoking/preprocess/48639-non-specific-probes-Illumina450k.csv"


pd <- readRDS(paste0(PREPROCESS_HERE,'pd.rds'))
setwd(IDAT_FOLDER_PATH)
rgset <- read.metharray(pd$Basename, verbose=T)

setwd(PREPROCESS_HERE)
saveRDS(rgset,file="rgset.rds")

#counts of starting sample numbers
N1 <- nrow(pd)
  
#if already have rgset made, just load it
#rgset <- readRDS(paste0(PREPROCESS_HERE,"rgset.rds"))
    
#### overall signal intensity
rawMSet <- preprocessRaw(rgset)
Meth<-getMeth(rawMSet)
Unmeth<-getUnmeth(rawMSet)

Meth[1:5,1:5]
Unmeth[1:5,1:5]

identical(pd$Basename,colnames(Meth))
Meth <- Meth[,as.character(pd$Basename)]
Unmeth <- Unmeth[,as.character(pd$Basename)]
pd$MQC <- log2(colMedians(Meth))
pd$UQC <- log2(colMedians(Unmeth))
rm(Meth,Unmeth,rawMSet)

pd$Array<-factor(pd$Array)
myColors<-c("dodgerblue", "firebrick1", "seagreen3")
palette(myColors)
pdf("MvsUplot.pdf")
  plot(pd$UQC, pd$MQC, main="M vs. U QC", pch=16, xlab="Log2 Median Unmethylated Intensity", ylab="Log2 Median Methylated Intensity", cex.lab=1.2, cex.main=2)
  plot(pd$UQC, pd$MQC, col=as.factor(pd$Slide), main="M vs. U QC by Slide", pch=16, xlab="Log2 Median Unmethylated Intensity", ylab="Log2 Median Methylated Intensity", cex.lab=1.2, cex.main=2)
  legend("topleft",levels(as.factor(pd$Slide)), fill=myColors)
  palette(graphColors)
  plot(pd$UQC, pd$MQC, col=pd$Array, main="M vs. U QC by Position", pch=16, xlab="Log2 Median Unmethylated Intensity", ylab="Log2 Median Methylated Intensity", cex.lab=1.2, cex.main=2)
  legend("bottomright",levels(pd$Array), fill=graphColors)
  palette(myColors)
  plot(pd$UQC, pd$MQC, col=as.factor(pd$Sample_Group), main="M vs. U QC by Sample Type", pch=16, xlab="Log2 Median Unmethylated Intensity", ylab="Log2 Median Methylated Intensity", cex.lab=1.2, cex.main=2)
  legend("topleft",levels(as.factor(pd$Sample_Group)), fill=myColors)
dev.off()

length(which(pd$UQC<11 | pd$MQC<11))
#37
saveRDS(pd,file="pd.rds")

```
